# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'datingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for datingApp
  # Firebase Pod
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  # Reacheable
  pod 'ReachabilitySwift'

  # Alamofire
  pod 'Alamofire'
  
end
